[package]
name = "zezaye"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.5.11"
intbits = "0.2.0"
nix = "0.22.0"
thiserror = "1.0.26"

[dev-dependencies]
gag = "1.0.0"
